### ISSUE TITLE
[HRtoVRChat] Simple float-based parameter

### ISSUE THREAD

**Issue by thetrueyoshifan** [200Tigersbloxed/UnityMods#10]
Having the ability to set a minimum and maximum threshold for heartrate, and then control a parameter from 0f to 1f would be super neat, as it would allow you to adjust the rate of animations, for things like breathing animations and the like. It could also be fun for emission-based changes, and the possibilities are nearly endless.

**Comment by 200Tigersbloxed** [comment]
Added in [v1.4.0 Pre-Release](https://github.com/200Tigersbloxed/UnityMods/releases/tag/hrtvrc-pre1.4.0)

Reopen issue if there's any issues, as it's untested.

**Comment by 200Tigersbloxed** [comment]
Reported issue of parameter falling back to either 1 or 0, will look into it later

**Comment by 200Tigersbloxed** [comment]
Fixed in v1.4.0
