### ISSUE TITLE
[HRtoVRChat] Write Defaults Off

### ISSUE THREAD

**Issue by untuned** [200Tigersbloxed/UnityMods#11]
Turning off Write Defaults seems to break the prefab, never transitioning from the disabled state.

VRChat [recommends that it be disabled](https://docs.vrchat.com/docs/avatars-30#write-defaults-on-states), but when doing so it breaks the transitions for some reason.

**Comment by untuned** [comment]
This can be solved by making the "disabled" layer look like this instead:

![example fix](https://untnd.me/2gp9tfskk)

By adding an "enabled" animation, the color properly switches over to the correct material.

**Comment by 200Tigersbloxed** [comment]
Not the greatest with animations, all the animations are hooked through the Any State node and not the Default Node. While you can hook them up again yourself, it'd be a little bit of time. I'll look into it, but note that it will be after #6 is implemented. Thank you for the report!

**Comment by untuned** [comment]
moving this to the OSC repo as the mod won't be updated for much longer
