### ISSUE TITLE
[HRtoVRChat] Parameters not being reset on close

### ISSUE THREAD

**Issue by untuned** [200Tigersbloxed/UnityMods#16]
When you stop the heart rate tracking using AMAPI, it does not seem to reset the parameters to their default values.
I am using `hyperate` for my `hrtype`.

![](https://untnd.me/cPEIk4UxU)

**Comment by 200Tigersbloxed** [comment]
I'll add this to the to-do-list for the next version. Can't believe I didn't notice that!

**Comment by 200Tigersbloxed** [comment]
Odd how `isHRConnected` is still connected too, I'll have to look into that as well.

**Comment by untuned** [comment]
> Odd how `isHRConnected` is still true too, I'll have to look into that as well.

Yeah, that was the weirdest bit! Clicking "StopHR" didn't do anything except stop updating it.

**Comment by untuned** [comment]
fixed in OSC version lol

**Comment by 200Tigersbloxed** [comment]
Still support mod, will fix in mod later

**Comment by 200Tigersbloxed** [comment]
Fixed in [v1.5.1](https://github.com/200Tigersbloxed/UnityMods/releases/tag/hrtvrc-v1.5.1)
